[phases.setup]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip"
]

[phases.install]
cmds = [
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"